import random

def difference(a,b):
    return(a-b)

a=int(input("Guess any number (1-20) : "))

b=random.randint(1,20)
print("Number Generated by PC :",b)

c=difference(a,b)
if c<0:
   c=c*(-1)
print("The difference between generated number and entered number : ",c)

if a==b:
    print("You have guessed the correct number")
elif c>=10:
    print("The number you guessed is very FAR")
elif(c>=5 and c<10):
    print("The number you guessed is little close")
elif(c>=2 and c<5):
    print("The number you guessed is very close")
else:
    print("Number is out of range")
